# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: oc-cmd@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'Sandbox20150220'
    version: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.17.8/openshift-client-linux-4.17.8.tar.gz'
    cmd: 'version'
- task: CopyFiles@2
  inputs:
    Contents: '$(HOME)/.kube/config'
    TargetFolder: '$(System.DefaultWorkingDirectory)'
- task: oc-cmd@3
  inputs:
    connectionType: 'Runtime Configuration'
    configurationPath: '$(System.DefaultWorkingDirectory)/config'
    version: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/4.17.8/openshift-client-linux-4.17.8.tar.gz'
    cmd: 'get pods'


